# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hass', '0002_auto_20161026_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('icon', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='hassentity',
            name='sub_tab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hass.SubTab'),
        ),
    ]
