# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hass', '0003_auto_20161026_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtab',
            name='tab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hass.Tab'),
        ),
    ]
